services:
  - type: web
    name: alphabet-learning
    env: python
    plan: free  # or 'starter' if using HD audio or expecting traffic
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py
    autoDeploy: true
    envVars:
      - key: OPENAI_API_KEY
        sync: false  # Set manually in Render dashboard
      - key: STREAMLIT_SERVER_HEADLESS
        value: true
      - key: STREAMLIT_SERVER_ENABLE_CORS
        value: false
      - key: STREAMLIT_BROWSER_GATHER_USAGE_STATS
        value: false
      - key: PYTHON_VERSION
        value: 3.10.0
